[package]
org = "ballerinax"
name = "azure_storage_service"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["azure", "storage", "blob", "file"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-storage-service"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
