[package]
org = "ballerinax"
name = "azure_storage_service"
version = "0.1.2-SNAPSHOT"
authors = ["Ballerina"]
export = ["azure_storage_service", "azure_storage_service.files", "azure_storage_service.blobs"]
keywords = ["content & files/file management & storage", "cost/paid", "vendor/microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-storage-service"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
