name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ stdlib-release-pipeline ]

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/release-package-connector-template.yml@2201.10.x
    secrets: inherit
    with:
      package-name: azure_storage_service
      package-org: ballerinax
